# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/analisar
Content-Type: application/json

{
      "texto": "O documento contém informações cadastrais do servidor."
}